# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialFD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationID', models.CharField(max_length=20)),
                ('apMAC', models.CharField(max_length=20)),
                ('rssi', models.IntegerField(default=-100)),
                ('channel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PartialFD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationID', models.CharField(max_length=20)),
                ('apMAC', models.CharField(max_length=20)),
                ('rssi', models.IntegerField(default=-100)),
                ('channel', models.IntegerField(default=0)),
                ('times', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RegParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyMU', models.CharField(max_length=20)),
                ('commonMU', models.CharField(max_length=20)),
                ('a', models.FloatField(default=0)),
                ('b', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateFD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationID', models.CharField(max_length=20)),
                ('apMAC', models.CharField(max_length=20)),
                ('rssi', models.IntegerField(default=-100)),
                ('channel', models.IntegerField(default=0)),
            ],
        ),
    ]
